"""
stem/schemas.py

Shared Pydantic models for the stem agent transformation pipeline.

This module is the single source of truth for all data contracts between
pipeline phases. Importing types from here — rather than defining them
in individual phase files — prevents drift and makes inter-phase contracts
explicit and enforceable.

Dependency order (no cycles):
    agent/tools.py  →  stem/schemas.py  →  stem/synthesize.py
                                        →  stem/generate.py

Design decisions:
- ToolName as Literal: forces synthesize to request tools by their exact
  registered names. Pydantic rejects any value not in the Literal — if the
  LLM generates "websearch" instead of "web_search", validation fails and
  synthesize retries automatically.
- AgentConfig field validators: enforce semantic quality, not just structure.
  A system_prompt of 10 chars is structurally valid but useless.
- ExecutableAgentConfig: validates the final config before it is persisted
  to disk. Distinct from AgentConfig — AgentConfig is what the stem reasons
  about, ExecutableAgentConfig is what the agent executes.
"""

from typing import Literal, get_args

from pydantic import BaseModel, field_validator

from agent.tools import AGENT_TOOLS

# ToolName is derived directly from AGENT_TOOLS — the single source of truth.
# If a tool is added to agent/tools.py, it automatically becomes requestable
# by the stem without any changes here.
ToolName = Literal[tuple(AGENT_TOOLS.keys())]  # type: ignore[valid-type]

# Human-readable list for prompts and error messages.
TOOL_NAMES: list[str] = list(get_args(ToolName))


class AgentConfig(BaseModel):
    """
    Structured configuration generated by the synthesize phase.

    Represents what the stem decided the specialized agent should be.
    Field validators enforce minimum semantic quality — structure alone
    is not sufficient for a useful agent.
    """

    domain: str
    identity: str
    system_prompt: str
    tools: list[ToolName]  # type: ignore[valid-type]
    accepts: list[str]
    rejects: list[str]
    stop_criteria: str
    quality_criteria: str

    @field_validator("system_prompt")
    @classmethod
    def system_prompt_must_be_substantial(cls, v: str) -> str:
        if len(v) < 500:
            raise ValueError(
                f"system_prompt too short ({len(v)} chars). "
                "Must encode real expert knowledge, not generic advice."
            )
        return v

    @field_validator("accepts", "rejects")
    @classmethod
    def lists_must_be_non_empty(cls, v: list) -> list:
        if len(v) < 3:
            raise ValueError(
                f"Must have at least 3 items, got {len(v)}. "
                "A well-scoped agent must define clear acceptance boundaries."
            )
        return v

    @field_validator("stop_criteria", "quality_criteria")
    @classmethod
    def criteria_must_be_specific(cls, v: str) -> str:
        if len(v) < 50:
            raise ValueError(
                f"Criteria too vague ({len(v)} chars). "
                "Must be specific enough to guide agent behavior."
            )
        return v


class ExecutableAgentConfig(BaseModel):
    """
    Validated configuration for a fully constructed, executable agent.

    Produced by the generate phase after tool matching and metadata
    injection. This is the contract between the stem pipeline and the
    agent execution layer — if this validates, the agent can run.
    """

    domain: str
    identity: str
    system_prompt: str
    tools: list[str]  # Includes direct_answer — validated non-empty
    accepts: list[str]
    rejects: list[str]
    stop_criteria: str
    quality_criteria: str
    generated_by: str
    stem_model: str
    elapsed_stem: float

    @field_validator("tools")
    @classmethod
    def tools_must_not_be_empty(cls, v: list) -> list:
        if not v:
            raise ValueError("Agent must have at least one tool.")
        return list(dict.fromkeys(v))  # deduplicate preserving order

    @field_validator("system_prompt")
    @classmethod
    def system_prompt_must_not_be_empty(cls, v: str) -> str:
        if not v.strip():
            raise ValueError("system_prompt cannot be empty.")
        return v
